<a href="https://colab.research.google.com/github/UmidjonDev/Artificial_Intelligence_Related/blob/main/Numpy_Related_Assignment_Answers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np
print(np.version)
print(np.show_config)

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>
<function show at 0x7c059ef31f30>


#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
numbers=[2, 5, 8, 21, 32, 11]
numpyArray=np.array(numbers)
print(numpyArray)

[ 2  5  8 21 32 11]


#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [ ]:
numpyArrayZeros=np.zeros(9, dtype=int)
print(numpyArrayZeros)

[0 0 0 0 0 0 0 0 0]


#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
numbers=[2, 5, 8, 21, 32, 11]
names=["Umka", "Umidjon", "Sattorov"]
numpyArray=np.array(numbers)
numpyArrayNames=np.array(names)
print(numpyArray.size)
print(numpyArrayNames.itemsize)

6
32


#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
zerosArray=np.zeros(12, dtype=int)
zerosArray[5]=1
print(zerosArray)

[0 0 0 0 0 1 0 0 0 0 0 0]


#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
rangedArray=np.arange(20, 60, 1)
print(rangedArray)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
rangedArrayReverse=rangedArray[::-1]
print(rangedArrayReverse)

[59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36
 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20]


#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
arr=np.arange(12, 21, 1).reshape(3, 3)
print(arr)

[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
np.nonzero(np.array([3, 7, 0, 0, 9, 0]))

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
np.random.random([2, 2, 2])

array([[[0.97371058, 0.38386045],
        [0.65969554, 0.8420488 ]],

       [[0.69301521, 0.44728731],
        [0.06647293, 0.58294467]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
print(np.random.random([9, 9]).max())
print(np.random.random([9, 9]).min())

0.9934940399369822
0.0016988495457738173


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
np.nan
False
False
np.nan
True
False

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
npArray1=np.random.randint(200, size=(6, 3))
npArray2=np.random.randint(200, size=(3, 4))
multiplication=np.dot(npArray1, npArray2)
print(multiplication)
print(npArray1)
print(npArray2)

[[ 8909 30057  7392 16789]
 [36606 53766 18798 25407]
 [35059 29256 16440  7880]
 [39609 70560 34352 20860]
 [52329 76599 35618 25594]
 [32709 51894 17210 25381]]
[[122  32   5]
 [171  36 132]
 [ 40  27 160]
 [140 185 112]
 [167 146 181]
 [173  35 112]]
[[ 50 198  26 137]
 [ 57 168 120   0]
 [197 105  76  15]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

10

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
npArray1=np.random.randint(200, size=(3, 4))
npArray2=np.random.randint(200, size=(3, 4))
print(npArray1>npArray2)
print(npArray1>=npArray2)
print(npArray1<npArray2)
print(npArray1<=npArray2)

[[ True False False  True]
 [ True  True  True False]
 [False  True  True  True]]
[[ True False False  True]
 [ True  True  True False]
 [False  True  True  True]]
[[False  True  True False]
 [False False False  True]
 [ True False False False]]
[[False  True  True False]
 [False False False  True]
 [ True False False False]]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.nan
0
[-2.14748365e+09]

[-2147483650.0]

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
npArray1=np.random.randint(200, size=(1, 49))
npArray2=np.random.randint(200, size=(1, 14))
np.intersect1d(npArray1, npArray2)

array([103, 160])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
npArray=np.random.random([9,9])*100
print(np.trunc(npArray).astype(int))
print(np.floor(npArray).astype(int))

[[76  2 80 16 77  5  8 72 14]
 [54 45 54  4 31  9 29 86 73]
 [31 63 37 36 77 81  0 63 81]
 [20 80 60 77  0 88 44 77 40]
 [55 44 52 60 47 89 55  2 59]
 [13 33 56 61 32 47  2 63 55]
 [63 54 19 76 60 11 34 33 28]
 [64 61 89 52 33 97 53  3 52]
 [11 29 62 22 23 50 85 76 11]]
[[76  2 80 16 77  5  8 72 14]
 [54 45 54  4 31  9 29 86 73]
 [31 63 37 36 77 81  0 63 81]
 [20 80 60 77  0 88 44 77 40]
 [55 44 52 60 47 89 55  2 59]
 [13 33 56 61 32 47  2 63 55]
 [63 54 19 76 60 11 34 33 28]
 [64 61 89 52 33 97 53  3 52]
 [11 29 62 22 23 50 85 76 11]]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:
myMatrix=np.arange(0, 3, 3/9).astype(int).reshape(3, 3)
print(myMatrix)

[[0 0 0]
 [1 1 1]
 [2 2 2]]


#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
npArray1=np.random.randint(200, size=(1, 10))
print(np.sort(npArray1))

[[  4  11  48  54  73  84 134 138 177 178]]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [ ]:
npArray1=np.random.randint(200, size=(1, 49))
npArray2=np.random.randint(200, size=(1, 49))
print(np.allclose(npArray1, npArray2))
print(np.array_equal(npArray1, npArray2))

False
False


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [ ]:
npArray1=np.random.randint(200, size=(6, 3))
npArray2=np.random.randint(200, size=(3, 4))
multiplication=np.dot(npArray1, npArray2)

print(multiplication)

print(npArray1)
print(npArray2)

[[64367 44813 21697 24438]
 [29582 16367 14815 17289]
 [32173 14508 15458 22139]
 [37003 23325 13579 17014]
 [64626 47203 19735 21521]
 [57066 33616 20910 28762]]
[[124 111 163]
 [ 67 102  31]
 [ 28 158  51]
 [ 57  96  88]
 [125  84 181]
 [ 61 181 143]]
[[187 149  99  62]
 [114  17  79 123]
 [175 150   4  19]]


#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [ ]:
npArray1=np.random.randint(200, size=(1, 5))
npArray1[0][np.argmax(npArray1)]=0
print(npArray1)

[[ 66   0 178 117 147]]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
print(np.datetime64('now'))
tomorrow=np.datetime64('now')+np.timedelta64(1, 'D')
yesterday=np.datetime64('now')-np.timedelta64(1, 'D')
print(f'Tomorrow is ${tomorrow}' )
print(f'Yesterday is ${yesterday}' )

2023-08-22T11:34:38
Tomorrow is $2023-08-23T11:34:38
Yesterday is $2023-08-21T11:34:38


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
print(np.arange(np.datetime64('2016-01-01T00:00:00'), np.datetime64('2016-01-31T00:00:00'), dtype=np.datetime64(1, 'D')))

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [ ]:
npArray=np.random.random([9,9])*100
print(np.trunc(npArray).astype(int))
print(np.floor(npArray).astype(int))
print(npArray.astype(int))
print((npArray-npArray%1).astype(int))

[[77 34 92 71 55 26 22 53 22]
 [18 51 85 12 65 13 79 87 98]
 [ 1  8  3 42 71 23 98 34 67]
 [15 41 25 55 10 77 34 88 62]
 [38  9 26 85 95 44 92 30 10]
 [74 58 57  0 70  8 65  6 45]
 [10 67 45 64 85 78 55 81 41]
 [39 71 26 80 23 19 57 23 67]
 [25  9 98 99 25 23 65 89 38]]
[[77 34 92 71 55 26 22 53 22]
 [18 51 85 12 65 13 79 87 98]
 [ 1  8  3 42 71 23 98 34 67]
 [15 41 25 55 10 77 34 88 62]
 [38  9 26 85 95 44 92 30 10]
 [74 58 57  0 70  8 65  6 45]
 [10 67 45 64 85 78 55 81 41]
 [39 71 26 80 23 19 57 23 67]
 [25  9 98 99 25 23 65 89 38]]
[[77 34 92 71 55 26 22 53 22]
 [18 51 85 12 65 13 79 87 98]
 [ 1  8  3 42 71 23 98 34 67]
 [15 41 25 55 10 77 34 88 62]
 [38  9 26 85 95 44 92 30 10]
 [74 58 57  0 70  8 65  6 45]
 [10 67 45 64 85 78 55 81 41]
 [39 71 26 80 23 19 57 23 67]
 [25  9 98 99 25 23 65 89 38]]
[[77 34 92 71 55 26 22 53 22]
 [18 51 85 12 65 13 79 87 98]
 [ 1  8  3 42 71 23 98 34 67]
 [15 41 25 55 10 77 34 88 62]
 [38  9 26 85 95 44 92 30 10]
 [74 58 57  0 70  8 65  6 45]
 [10 67

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [10]:
matrixSimple1=np.array([1,2,3,4,5], dtype=int)
print(np.add.reduce(matrixSimple1))

15


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [ ]:
matrixSimple=np.array([1,2,3,4,5], dtype=int)
matrixSimple[::4]=0
print(matrixSimple)

[0 2 3 4 0]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [4]:
from numpy.lib.stride_tricks import as_strided
exerciseArray=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14], dtype=int)
changedArray=as_strided(exerciseArray, shape=(11, 4), strides=(8, 8))
print(changedArray)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [9]:
exerciseArray1=np.array([1,2,3, 3, 2, 1, 5, 4, 7, 9, 10, 9], dtype=int)
i=0
repeatableElementsArray=[]
bincountedArr=np.bincount(exerciseArray1)
while(i<=np.argmax(exerciseArray1)):
  if(bincountedArr[i]<=1):
    i+=1
    continue
  else:
    repeatableElementsArray+=[i]
    i+=1
print(repeatableElementsArray)

[1, 2, 3, 9]


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`